# Travis CI build pipeline
# --------------------------------------

os: linux
dist: xenial
language: csharp
solution: PipelineLib.sln
mono: none
dotnet: 5.0.301

before_scrip:
  - set -e
  - dotnet restore

script:
  - dotnet build -c Release